when:
  event: [push, manual]
  path:
    include: ["*.rs", "*.toml"]
steps:
  test:
    image: rust:trixie
    commands:
      - apt update && apt install -y protobuf-compiler
      - cargo build --release --no-default-features
      - cargo test --release
      - cargo test --features documented
